'use strict';

/**
 * Doxygen configuration options.
 */

export default class DoxygenConfig
{
	/**
	 * Path to the Doxyfile used by Doxygen.
	 * @type {String}
	 */

	doxyfile;

	/**
	 * Input paths used by Doxygen. Values in this array will be assigned to `INPUT` in the Doxyfile.
	 * @type {String[]}
	 */

	inputPaths;

	/**
	 * Output path for XML generated by Doxygen. This value will be assigned to `XML_OUTPUT` in the Doxyfile.
	 * @type {String}
	 */

	outputPath;

	/**
	 * Initializes a new DoxygenConfig.
	 * @param {Object} config - Object containing values to initialize the DoxygenConfig with.
	 * @param {String} config.doxyfile - Path to the Doxyfile used by Doxygen.
	 * @param {String[]} config.inputPaths - Input paths used by Doxygen. Values in this array will be assigned to `INPUT` in the Doxyfile.
	 * @param {String} config.outputPath - Output path for XML generated by Doxygen. This value will be assigned to `XML_OUTPUT` in the Doxyfile.
	 */

	constructor(config)
	{
		if (config)
		{
			this.doxyfile = config.doxyfile;
			this.inputPaths = config.inputPaths;
			this.outputPath = config.outputPath;
		}
	}
}