'use strict';

/**
 * Configuration for a project.
 */

export default class ProjectConfig
{
	/**
	 * Display name of the project.
	 * @type {String}
	 */

	name;

	/**
	 * Input paths to source code processed by Doxygen. Values in this array will be assigned to `INPUT` in the Doxyfile.
	 * @type {String[]}
	 */

	sourceInputPaths;

	/**
	 * Relative path from the XML output root where XML for the project will be generated by Doxygen.
	 * @type {String}
	 */

	xmlSubPath;

	/**
	 * Relative path from the site root where the project is located.
	 * @type {String}
	 */

	siteSubPath

	/**
	 * Initializes a new ProjectConfig.
	 * @param {Object} config - Object containing values to initialize the ProjectConfig with.
	 * @param {String} config.name - Display name of the project.
	 * @param {String[]} config.sourceInputPaths - Input paths to source code processed by Doxygen. Values in this array will be assigned to `INPUT` in the Doxyfile.
	 * @param {String} config.xmlSubPath - Relative path from the XML output root where XML for the project will be generated by Doxygen.
	 * @param {String} config.siteSubPath - Relative path from the site root where the project is located.
	 */

	constructor(config)
	{
		if (config)
		{
			this.name = config.name;
			this.sourceInputPaths = config.sourceInputPaths;
			this.xmlSubPath = config.xmlSubPath;
			this.siteSubPath = config.siteSubPath;
		}
	}
}